<#
.SYNOPSIS
  Install nginx for Windows and set it up as a reverse proxy in front of
  the Blender-AI API (port 3001) and the frontend (static files).

.DESCRIPTION
  - Downloads nginx/Windows zip (no installer)
  - Installs to C:\nginx
  - Generates a self-signed dev cert if DigiCert is not present
  - Installs nginx as a Windows Service via NSSM
  - Opens firewall ports 80, 443, 8443
#>
[CmdletBinding()]
param(
    [string]$InstallDir  = "C:\nginx",
    [string]$CertDir     = "C:\blender-ai\certs",
    [string]$FrontendDir = "C:\blender-ai\frontend",
    [string]$ApiUpstream = "http://127.0.0.1:3001",
    [int]$ApiPort        = 8443
)

$ErrorActionPreference = "Stop"

# --- 1. Download nginx ---------------------------------------------------
$nginxExe = "$InstallDir\nginx.exe"
if (-not (Test-Path $nginxExe)) {
    Write-Host "[1/5] Downloading nginx for Windows..." -ForegroundColor Yellow
    New-Item -ItemType Directory -Path $InstallDir -Force | Out-Null
    # Latest stable as of 2025; pinned to 1.27.5 (works on Server 2025)
    $url = "http://nginx.org/download/nginx-1.27.5.zip"
    $tmp = "$env:TEMP\nginx.zip"
    Invoke-WebRequest -Uri $url -OutFile $tmp -UseBasicParsing
    Expand-Archive -Path $tmp -DestinationPath "$env:TEMP\nginx-extract" -Force
    # zip 顶层就是 nginx-1.27.5/
    $extracted = Get-ChildItem "$env:TEMP\nginx-extract" -Directory | Select-Object -First 1
    # 把所有内容挪到 $InstallDir
    Get-ChildItem $extracted.FullName -Force | ForEach-Object {
        Move-Item $_.FullName $InstallDir -Force
    }
    Remove-Item $tmp, "$env:TEMP\nginx-extract" -Recurse -Force -ErrorAction SilentlyContinue
    Write-Host "  Installed nginx to $InstallDir" -ForegroundColor Green
} else {
    Write-Host "[1/5] nginx already present" -ForegroundColor Green
}

# --- 2. Certs ------------------------------------------------------------
New-Item -ItemType Directory -Path $CertDir -Force | Out-Null
$pemFile = "$CertDir\blender-ai.com.pem"
$keyFile = "$CertDir\blender-ai.com.key"
if (-not (Test-Path $pemFile) -or -not (Test-Path $keyFile)) {
    Write-Host "[2/5] No cert found, generating self-signed for dev..." -ForegroundColor Yellow
    Write-Host "      (Replace with DigiCert cert before going live)" -ForegroundColor Red
    $pfxPass = ConvertTo-SecureString "devonly" -AsPlainText -Force
    $cert = New-SelfSignedCertificate `
        -DnsName "blender-ai.com","www.blender-ai.com","localhost" `
        -CertStoreLocation "cert:\LocalMachine\My" `
        -NotAfter (Get-Date).AddDays(365) `
        -KeyUsage DigitalSignature,KeyEncipherment `
        -KeyAlgorithm RSA -KeyLength 2048
    $pfxPath = "$CertDir\blender-ai.com.pfx"
    Export-PfxCertificate -Cert $cert -FilePath $pfxPath -Password $pfxPass | Out-Null
    # 转 PEM (openssl 是 git for windows 自带的)
    $gitOpenssl = "C:\Program Files\Git\usr\bin\openssl.exe"
    if (Test-Path $gitOpenssl) {
        & $gitOpenssl pkcs12 -in $pfxPath -nocerts -nodes -passout pass:devonly -out $keyFile 2>$null
        & $gitOpenssl pkcs12 -in $pfxPath -clcerts -nokeys -passin pass:devonly -out $pemFile 2>$null
        Write-Host "  Generated self-signed cert + key" -ForegroundColor Green
    } else {
        Write-Host "  WARN: openssl not found, cert not exported to PEM" -ForegroundColor Yellow
    }
    Remove-Item $pfxPath -ErrorAction SilentlyContinue
} else {
    Write-Host "[2/5] Cert files present" -ForegroundColor Green
}

# --- 3. nginx config -----------------------------------------------------
$confDir = "$InstallDir\conf"
$siteConf = "$confDir\conf.d\blender-ai.conf"
New-Item -ItemType Directory -Path "$confDir\conf.d" -Force | Out-Null
$confText = @"
# Generated by install-nginx.ps1 - edit and run nginx -s reload
worker_processes  auto;
error_log  $InstallDir\logs\error.log warn;
pid        $InstallDir\logs\nginx.pid;
events { worker_connections  1024; }
http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile      on;
    keepalive_timeout  65;
    client_max_body_size 50m;   # 3D model uploads

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent"';
    access_log  $InstallDir\logs\access.log  main;

    # ---------- Frontend (port 443) ----------
    server {
        listen      443 ssl;
        http2       on;
        server_name www.blender-ai.com blender-ai.com;

        ssl_certificate     $pemFile;
        ssl_certificate_key $keyFile;
        ssl_protocols       TLSv1.2 TLSv1.3;
        add_header Strict-Transport-Security "max-age=31536000" always;

        root   $FrontendDir;
        index  index.html;
        location / {
            try_files `$uri `$uri/ /index.html;
        }
        location /assets/ { expires 1y; add_header Cache-Control "public, immutable"; }
    }

    # ---------- HTTP → HTTPS redirect ----------
    server {
        listen      80;
        server_name www.blender-ai.com blender-ai.com;
        return 301  https://`$host`$request_uri;
    }
}
"@
# API 在另一个 server block (用 $ApiPort),引用同一对证书
$apiConf = @"

# ---------- API (port $ApiPort) ----------
server {
    listen      $ApiPort ssl;
    http2       on;
    server_name www.blender-ai.com blender-ai.com;

    ssl_certificate     $pemFile;
    ssl_certificate_key $keyFile;
    ssl_protocols       TLSv1.2 TLSv1.3;

    # Public: plugin + downloads
    location /v1/ {
        proxy_pass         $ApiUpstream;
        proxy_http_version 1.1;
        proxy_set_header   Host              `$host;
        proxy_set_header   X-Real-IP         `$remote_addr;
        proxy_set_header   X-Forwarded-For   `$proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto `$scheme;
        proxy_read_timeout 900s;
        proxy_send_timeout 900s;
        proxy_buffering    off;
    }
    location = /health {
        proxy_pass $ApiUpstream/health;
        access_log off;
    }
}
"@

[System.IO.File]::WriteAllText("$confDir\nginx.conf", $confText, [System.Text.UTF8Encoding]::new($false))
[System.IO.File]::WriteAllText($siteConf,         $apiConf,  [System.Text.UTF8Encoding]::new($false))
# conf/nginx.conf 里的 include 取消 conf.d/*.conf 注释
$mainConf = Get-Content "$confDir\nginx.conf" -Raw
if ($mainConf -notmatch "include.*conf\.d") {
    $patched = $mainConf -replace '(http\s*{\s*\n)', "`$1    include $confDir\conf.d/*.conf;`n"
    [System.IO.File]::WriteAllText("$confDir\nginx.conf", $patched, [System.Text.UTF8Encoding]::new($false))
}
New-Item -ItemType Directory -Path "$InstallDir\logs" -Force | Out-Null
Write-Host "[3/5] nginx config written" -ForegroundColor Green

# --- 4. nginx as Windows Service via NSSM --------------------------------
Write-Host "[4/5] Registering nginx service..." -ForegroundColor Yellow
$NssmExe = "C:\Tools\nssm\nssm.exe"
if (-not (Test-Path $NssmExe)) {
    throw "NSSM not found at $NssmExe. Run install-api-service.ps1 first (it downloads NSSM)."
}
if (Get-Service nginx -ErrorAction SilentlyContinue) {
    & $NssmExe stop nginx 2>$null
    & $NssmExe remove nginx confirm
}
& $NssmExe install nginx "$nginxExe"
& $NssmExe set nginx AppDirectory  $InstallDir
& $NssmExe set nginx DisplayName   "Blender-AI nginx"
& $NssmExe set nginx Description   "Reverse proxy: 443→frontend, $ApiPort→api"
& $NssmExe set nginx Start         SERVICE_AUTO_START
& $NssmExe set nginx AppStdout     "$InstallDir\logs\service-stdout.log"
& $NssmExe set nginx AppStderr     "$InstallDir\logs\service-stderr.log"
& $NssmExe set nginx AppRotateFiles 1
& $NssmExe set nginx AppRotateBytes 10485760
& $NssmExe set nginx AppExit       Default Restart
& $NssmExe set nginx AppRestartDelay 5000
Start-Service nginx
Start-Sleep -Seconds 2
$svc = Get-Service nginx
Write-Host "  nginx status: $($svc.Status)" -ForegroundColor $(if ($svc.Status -eq 'Running') { 'Green' } else { 'Red' })
if ($svc.Status -ne 'Running') {
    Get-Content "$InstallDir\logs\error.log" -ErrorAction SilentlyContinue | Select-Object -Last 20
    throw "nginx failed to start"
}

# --- 5. Firewall --------------------------------------------------------
Write-Host "[5/5] Opening firewall..." -ForegroundColor Yellow
$ports = @(80, 443, $ApiPort)
foreach ($p in $ports) {
    $ruleName = "Blender-AI TCP $p"
    if (Get-NetFirewallRule -DisplayName $ruleName -ErrorAction SilentlyContinue) {
        Write-Host "  rule '$ruleName' already exists" -ForegroundColor Gray
        continue
    }
    New-NetFirewallRule -DisplayName $ruleName -Direction Inbound -Protocol TCP -LocalPort $p -Action Allow -Profile Any | Out-Null
    Write-Host "  opened TCP $p" -ForegroundColor Green
}

Write-Host ""
Write-Host "=== nginx installed and running ===" -ForegroundColor Green
Write-Host "Frontend:  https://www.blender-ai.com/  (after DNS points to this server)"
Write-Host "API:       https://www.blender-ai.com:$ApiPort/v1/  (used by Blender plugin)"
Write-Host "Local:     http://127.0.0.1:80/  +  http://127.0.0.1:$ApiPort/v1/"
